apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::338556495561:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-S2MLcrqDW5Sp
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
      - userarn: arn:aws:iam::338556495561:user/tim
        username: tim
kind: ConfigMap
metadata:
  creationTimestamp: "2025-08-06T07:25:54Z"
  name: aws-auth
  namespace: kube-system
  uid: c5685247-7028-432c-b8a8-fba8ae17db5c
